controller:
  name: controller

  ingressClassResource:
    name: nginx-internal
    enabled: true
    default: false #set to true when deleting old external ingress
    controllerValue: "k8s.io/ingress-nginx-internal"

  ingressClass: nginx-internal

  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    loadBalancerIP: "10.10.30.75"
    annotations:
      cloudprovider.harvesterhci.io/ipam: pool
      cloudprovider.harvesterhci.io/ippool: global-ip-pool

  publishService:
    enabled: true