controller:
  name: controller

  ingressClassResource:
    name: nginx-internal
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx-internal"

  ingressClass: nginx-internal

  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    annotations:
      metallb.io/loadBalancerIPs: "10.10.30.50"

  publishService:
    enabled: true