controller:
  name: controller

  ingressClassResource:
    name: nginx-internal
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-internal"

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local  # Preserve source IP
    loadBalancerIP: "10.10.30.75"
    annotations:
      metallb.universe.tf/address-pool: internal-pool

  publishService:
    enabled: true

  config:
    use-forwarded-headers: "true"
    enable-real-ip: "true"