controller:
  name: controller

  ingressClassResource:
    name: nginx-internal
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-internal"

  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    loadBalancerIP: "10.10.30.75"

  publishService:
    enabled: true