controller:
  name: controller

  ingressClassResource:
    name: nginx-internal
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-internal"

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local  # Preserve source IP
    annotations:
      metallb.io/loadBalancerIPs: "10.10.30.75"

  publishService:
    enabled: true

  config:
    use-forwarded-headers: "true"
    enable-real-ip: "true"