apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static-ingress-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.10.30.99/32
    - 10.10.30.50/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - static-ingress-pool
  nodeSelectors:
    - matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists