apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static-ingress-pool
  namespace: metallb
spec:
  addresses:
    - 10.10.30.75/32
    - 10.10.30.80/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb
spec:
  ipAddressPools:
    - static-ingress-pool