# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: rancher-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.10.50.25/32  # Single IP for Rancher
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: rancher-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - rancher-pool