apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - authentik-ingress.yaml
  - authentik-sealed-secrets.yaml

# Labels applied to all resources
labels:
  - includeSelectors: false
    pairs:
      managed-by: fleet