apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-internal
  namespace: unifi
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
        - unifi.lab.ghostlabz.net
      secretName: ghostlabz-wildcard-tls
  rules:
    - host: unifi.lab.ghostlabz.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unifi-controller
                port:
                  number: 8443