controller:
  name: controller
  kind: DaemonSet

  ingressClassResource:
    name: nginx-external
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-external"

  ingressClass: nginx-external

  service:
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: "10.10.30.80"
    annotations:
      cloudprovider.harvesterhci.io/ipam: pool
      cloudprovider.harvesterhci.io/ippool: global-ip-pool
    healthCheckNodePort: 0

  publishService:
    enabled: true

  config:
    use-forwarded-headers: "true"
    enable-real-ip: "true"
    enable-modsecurity: "true"
    enable-owasp-modsecurity-crs: "true"
