apiVersion: v1
kind: Namespace
metadata:
  name: ingress-external
  labels:
    kubernetes.io/metadata.name: ingress-external
    name: ingress-external
    role: ingress
    trust-boundary: external
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted