apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  # ClusterIssuers
  - clusterissuer-letsencrypt-prod.yaml

  # Certificates
  - media-wildcard-cert.yaml

  # Secrets (encrypted/sealed)
  - cloudflare-secret.yaml

labels:
  - pairs:
      managed-by: fleet
      component: cert-manager
