apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama

resources:
  - ingress.yaml
  - open-webui.yaml
  - sealed-secrets.yaml
  - searxng.yaml

# Labels applied to all resources
labels:
  - includeSelectors: false
    pairs:
      managed-by: fleet