controller:
  name: controller
  kind: DaemonSet

  ingressClassResource:
    name: nginx-external
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-external"

  ingressClass: nginx-external

  nodeSelector:
    dedicated: edge

  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "edge"
      effect: "NoSchedule"

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      kube-vip.io/ignore: "true"
      cloudprovider.harvesterhci.io/ipam: pool
      loadbalancer.harvesterhci.io/network: default/dmz

  publishService:
    enabled: true