container_runtime: containerd

image:
  tag: "v1.6.4"

agent:
  acquisition:
  - namespace: ingress-external
    podName: nginx-external-*
    program: nginx
    poll_without_inotify: true

  env:
    - name: COLLECTIONS
      value: "crowdsecurity/nginx"

lapi:
  env:
    - name: DISABLE_ONLINE_API
      value: "false"

  # Persistent storage for the database
  persistentVolume:
    config:
      enabled: true
      storageClassName: longhorn-2r
      size: 1Gi
    data:
      enabled: true
      storageClassName: longhorn-2r
      size: 1Gi