apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
  - ingress.yaml
  - codeserver-sealed-secret.yaml

# Labels applied to all resources
labels:
  - includeSelectors: true
    pairs:
      app: home-assistant
      managed-by: fleet