apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
  - velero-sealed-secrets.yaml
  - volumesnapshotclass.yaml
  - backup-schedules.yaml

labels:
  - includeSelectors: false
    pairs:
      managed-by: fleet
      component: velero