apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

configMapGenerator:
  - name: media-mover-script
    files:
      - mover.sh

resources:
  - mover.yaml
  - mover-secrets.yaml

labels:
  - includeSelectors: false
    pairs:
      managed-by: fleet