# --- EXTERNAL (Jellyfin) ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-external
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx # <--- Public Nginx
  tls:
    - hosts:
        - ghostlabz.net
        - request.ghostlabz.net
      secretName: ghostlabz-wildcard-tls
  rules:
    - host: ghostlabz.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: jellyfin, port: { number: 8096 } } }
    - host: request.ghostlabz.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: jellyseerr, port: { number: 5055 } } }

---
# --- INTERNAL (SABnzbd / Sonarr / Radarr) ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-internal
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
        - sonarr.lab.ghostlabz.net
        - sabnzbd.lab.ghostlabz.net
        - prowlarr.lab.ghostlabz.net
        - profilarr.lab.ghostlabz.net
        - radarr.lab.ghostlabz.net
      secretName: ghostlabz-wildcard-tls
  rules:
    - host: sonarr.lab.ghostlabz.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: sonarr, port: { number: 8989 } } }
    - host: sabnzbd.lab.ghostlabz.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: sabnzbd, port: { number: 8080 } } }
    - host: prowlarr.lab.ghostlabz.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: prowlarr, port: { number: 9696 } } }
    - host: profilarr.lab.ghostlabz.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: profilarr, port: { number: 6868 } } }
    - host: radarr.lab.ghostlabz.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: radarr, port: { number: 7878 } } }
